### ISSUE TITLE
TypeError: can't access property "id", this.sessionInfo is null

### ISSUE THREAD

**Issue by tsygankov** [prageeth/browser-tab-tracker#11]
Hi!

Thanks for sharing the component!

Would be nice to add a method to check if the component is initialized ( e.g. isInitialized() ). Currently, it throws an error if you try to access 'sessionId' before initialization, and looks that there is no other way to check if the session was started. In my case, I need to start session after specific user action. If acceptable, please change 'get sessionId()' and 'get tabId()' methods, so that they would return null\undefined, if session is not yet initialized.

Error message:
`TypeError: can't access property "id", this.sessionInfo is null`

Thanks!

**Comment by prageeth** [comment]
Hi @tsygankov, thanks for reporting the issue. I've just upgrade the packages to the latest versions and also fixed the issue you mentioned, specifically:

- Added null checks for the getters
- Added new getter to check if the service is initialized

You can see the changes here:
https://github.com/pureartisan/browser-session-tabs/pull/15

Since this is a breaking change from the previous behaviour (it was originally intended to throw an error), I've bumped the version by a major (`v3.0.0`)

https://github.com/pureartisan/browser-session-tabs/releases/tag/v3.0.0

I will close this issue for now. If you also find anything else you'd like to change, please feel free to send through any PRs.

Thanks!
